# Configuration file for http://goreleaser.com

before:
  hooks:
    - ./update_version.sh

builds:
  - goos:
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - GOFLAGS=-mod=mod

archives:
  - files:
      - README.md
      - plugin.yaml

changelog:
  sort: asc
