# GitHub Actions Workflow definition to automatically create a new release for each new Git tag

name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        # https://github.com/actions/checkout
      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Setup Go
        # https://github.com/actions/setup-go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run GoReleaser
        # https://github.com/goreleaser/goreleaser-action
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
