# GitHub Actions Workflow definition to automatically create a new Git tag on each push to master

name: tag

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        # https://github.com/actions/checkout
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: fregante/setup-git-user@v2

      - name: tag
        id: tag
        uses: jenkins-x-plugins/jx-release-version@v2.7.3
        with:
          tag: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
